##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://collectionbuilder.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
#baseurl: /collectionbuilder-gh 
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-gh

##########
# SITE SETTINGS
#
# title of site appears in banner
title: From Minorca to Florida
# tagline a short phrase that will appear throughout the site in the top banner
tagline: A Digital Archive of Diaspora and Memory in St. Augustine
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "digital project dedicated to documenting the Minorcan presence in St. Augustine, Florida. In 1768, over 1,400 Mediterranean settlers—among whom the largest group came from the island of Minorca—were brought to Florida by Andrew Turnbull to establish an agricultural colony in New Smyrna. Once there, they were subjected to harsh conditions and forced into indentured labor. After nearly a decade, the colony collapsed, and in 1777, the surviving settlers walked almost 70 miles north to St. Augustine. There, they petitioned British governor Patrick Tonyn for refuge and were allowed to settle permanently, forming a lasting community. The project aims to gather and digitally preserve primary documents—many of them housed across various cultural institutions in St. Augustine—that trace this diasporic journey, settlement, and cultural memory."
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Susanna Alles-Torrent

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the csv file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
# metadata-csv: https://docs.google.com/spreadsheets/d/e/2PACX-1vQMzyVLEpQYNCYxsrS1RcHJWpDJSiHTQKZ5rUQlWoI3rrKRkutyqgZNLFMkxTLiFB1WKDrlR_J-Xo_G/pub?output=csv
metadata: CB_minorcans

##########
# Site/Organization Branding 
#   Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#
# organization-name: "University of Miami"
# organization-link: https://dh.miami.edu/
# organization-logo-banner: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil.png
# organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md]
# compress CSS output
sass:
  style: compressed
